# Generated by Django 3.1.4 on 2021-02-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, default='', max_length=50)),
                ('title1', models.CharField(default='', max_length=50)),
                ('title2', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='shop_controls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, default='', max_length=50)),
                ('sortedBy', models.CharField(default='', max_length=50)),
                ('title2', models.CharField(blank=True, default='', max_length=50)),
                ('quantity', models.CharField(default='', max_length=50)),
                ('title3', models.CharField(blank=True, default='', max_length=50)),
                ('pages', models.CharField(default='', max_length=50)),
                ('lastOfPage_number', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
