# Generated by Django 3.1.4 on 2021-02-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_apps', '0002_shop_banner_shop_controls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop_controls',
            old_name='quantity',
            new_name='NumberOfshowPruduct',
        ),
        migrations.AlterField(
            model_name='shop_controls',
            name='lastOfPage_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
