# Generated by Django 3.1.4 on 2021-02-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_apps', '0004_shop_controls_lastofpage_number2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_controls',
            name='lastOfPage_number2',
        ),
        migrations.AlterField(
            model_name='shop_controls',
            name='lastOfPage_number',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
