# Generated by Django 3.1.4 on 2021-02-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_apps', '0005_auto_20210214_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopPrduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='shop_productImgs/')),
                ('p_name', models.CharField(max_length=50)),
                ('p_price_usd', models.IntegerField()),
            ],
        ),
    ]
