# Generated by Django 3.1.4 on 2021-04-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_apps', '0006_shopprduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprduct',
            name='product_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
