# Generated by Django 3.1.4 on 2021-04-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_apps', '0008_auto_20210420_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordershoped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('product_Code', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
