# Generated by Django 3.1.4 on 2021-02-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('title1', models.CharField(max_length=50)),
                ('title2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='blog_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=50)),
                ('img', models.ImageField(upload_to='blogImg/')),
                ('date', models.DateTimeField(blank=True)),
                ('author_by', models.CharField(max_length=50)),
                ('like', models.CharField(max_length=50)),
                ('cmnt', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('describe', models.TextField(max_length=250)),
                ('button', models.CharField(max_length=50)),
            ],
        ),
    ]
