# Generated by Django 3.1.4 on 2021-02-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfileApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bannarLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('title1', models.CharField(max_length=50)),
                ('title2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginHeader', models.CharField(max_length=50)),
                ('logintitle', models.CharField(max_length=50)),
                ('registerHeader', models.CharField(max_length=50)),
                ('hint', models.CharField(max_length=50)),
                ('RegisterTitle', models.CharField(max_length=50)),
            ],
        ),
    ]
