# Generated by Django 3.1.4 on 2021-04-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfileApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_photo',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
