# Generated by Django 3.1.4 on 2021-04-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfileApp', '0002_user_photo_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_photo',
            name='time',
        ),
    ]
