# Generated by Django 3.1.4 on 2021-04-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfileApp', '0003_remove_user_photo_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_photo',
            name='ids',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
