# Generated by Django 3.1.4 on 2021-03-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfileApp', '0003_allregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allregister',
            name='userName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
