# Generated by Django 3.1.4 on 2021-04-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfileApp', '0005_remove_user_photo_ids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Photo',
        ),
    ]
