# Generated by Django 3.1.4 on 2021-04-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfileApp', '0006_delete_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allregister',
            name='userConPass',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
