# Generated by Django 3.1.4 on 2021-02-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_apps', '0003_contact_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_messagesHeade_button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('button_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='msgBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('L_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=14)),
                ('location', models.CharField(max_length=150)),
                ('comment', models.TextField(blank=True, max_length=300)),
            ],
        ),
    ]
