# Generated by Django 3.1.4 on 2021-02-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_apps', '0004_contact_messagesheade_button_msgbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgbox',
            name='L_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='msgbox',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='msgbox',
            name='f_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='msgbox',
            name='location',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='msgbox',
            name='phone',
            field=models.IntegerField(default=''),
        ),
    ]
