# Generated by Django 3.1.4 on 2021-02-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_apps', '0009_auto_20210216_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgbox',
            name='L_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='msgbox',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='msgbox',
            name='location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='msgbox',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
