# Generated by Django 3.1.4 on 2021-02-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='abou_banner',
            new_name='about_banner',
        ),
    ]
