# Generated by Django 3.1.4 on 2021-02-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_apps', '0002_auto_20210212_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_number', models.CharField(max_length=9)),
                ('quantity_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='about_designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=50)),
                ('img', models.ImageField(upload_to='designerImage/')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='about_stroy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='storyImage/')),
                ('story', models.TextField(max_length=1000)),
            ],
        ),
    ]
