# Generated by Django 3.1.4 on 2021-02-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_apps', '0003_about_counter_about_designer_about_stroy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_footerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_title', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=15)),
                ('logo', models.ImageField(upload_to='logoimage/')),
            ],
        ),
    ]
