# Generated by Django 3.1.4 on 2021-02-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_apps', '0004_header_footerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='header_footerdata',
            name='copyRight',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='header_footerdata',
            name='copyRightBy',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='header_footerdata',
            name='footerContact_header',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='header_footerdata',
            name='footerContact_location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='header_footerdata',
            name='footerContact_mail',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='header_footerdata',
            name='footerContact_telePhone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='header_footerdata',
            name='footerContact_webSite',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='header_footerdata',
            name='footerLogo_describ',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='header_footerdata',
            name='footerLogo_describ_2',
            field=models.TextField(default='', max_length=500),
        ),
    ]
