# Generated by Django 3.1.4 on 2021-04-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feature_header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('menu1', models.CharField(max_length=50)),
                ('menu2', models.CharField(max_length=50)),
                ('menu3', models.CharField(max_length=50)),
                ('menu4', models.CharField(max_length=50)),
                ('menu5', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='feature_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(upload_to='feature_images/')),
                ('product_title', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('product_code', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Header_footerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_title', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=15)),
                ('logo', models.ImageField(upload_to='logoimage/')),
                ('footerLogo_describ', models.TextField(default='', max_length=500)),
                ('footerLogo_describ_2', models.TextField(default='', max_length=500)),
                ('footerContact_header', models.CharField(default='', max_length=50)),
                ('footerContact_location', models.CharField(default='', max_length=200)),
                ('footerContact_telePhone', models.CharField(default='', max_length=50)),
                ('footerContact_mail', models.CharField(default='', max_length=50)),
                ('footerContact_webSite', models.CharField(default='', max_length=70)),
                ('copyRight', models.CharField(default='', max_length=50)),
                ('copyRightBy', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LatestProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='latest_img/')),
                ('P_name', models.CharField(max_length=50)),
                ('P_price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='My_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=50)),
                ('img', models.ImageField(upload_to='blogImg/')),
                ('date', models.DateTimeField(blank=True)),
                ('author_by', models.CharField(max_length=50)),
                ('like', models.CharField(max_length=50)),
                ('cmnt', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('describe', models.TextField(max_length=250)),
                ('button', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='newProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='launchImages/')),
                ('productName', models.CharField(max_length=50)),
                ('details', models.TextField(max_length=250)),
                ('launchTitle', models.CharField(max_length=50)),
                ('month', models.CharField(default='', max_length=5)),
                ('day', models.CharField(default='', max_length=5)),
                ('year', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ordered_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('product_Code', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='shipping_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('details', models.TextField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='slider_part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('Header', models.CharField(max_length=30)),
                ('describe', models.TextField(max_length=500)),
                ('left_button', models.CharField(max_length=50)),
                ('right_button', models.CharField(max_length=50)),
                ('slider_images', models.ImageField(default='', upload_to='slider_img/')),
            ],
        ),
        migrations.CreateModel(
            name='special_part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='special_images/')),
                ('product_head', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=250)),
                ('button_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=50)),
                ('personName', models.CharField(max_length=50)),
                ('personTitle', models.CharField(max_length=50)),
                ('personImg', models.ImageField(upload_to='testimonial/')),
                ('describe', models.TextField(max_length=220)),
                ('signature', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User_Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='profilepic/')),
                ('time', models.TimeField()),
            ],
        ),
    ]
