# Generated by Django 3.1.4 on 2021-01-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header_footerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_title', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=15)),
                ('logo', models.ImageField(upload_to='logoimage/')),
                ('footerLogo_describ', models.TextField(max_length=500)),
                ('footerContact_header', models.CharField(max_length=50)),
                ('footerContact_location', models.CharField(max_length=200)),
                ('footerContact_telePhone', models.CharField(max_length=50)),
                ('footerContact_mail', models.CharField(max_length=50)),
                ('footerContact_webSite', models.CharField(max_length=70)),
            ],
        ),
    ]
