# Generated by Django 3.1.4 on 2021-04-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='profilepic/')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user_photo',
            name='by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
