# Generated by Django 3.1.4 on 2021-01-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header_footerdata',
            name='footerContact_header',
        ),
        migrations.RemoveField(
            model_name='header_footerdata',
            name='footerContact_location',
        ),
        migrations.RemoveField(
            model_name='header_footerdata',
            name='footerContact_mail',
        ),
        migrations.RemoveField(
            model_name='header_footerdata',
            name='footerContact_telePhone',
        ),
        migrations.RemoveField(
            model_name='header_footerdata',
            name='footerContact_webSite',
        ),
        migrations.RemoveField(
            model_name='header_footerdata',
            name='footerLogo_describ',
        ),
    ]
