# Generated by Django 3.1.4 on 2021-04-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_user_photo_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Photo',
        ),
    ]
