# Generated by Django 3.1.4 on 2021-01-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_auto_20210128_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='header_footerdata',
            name='footerLogo_describ_2',
            field=models.TextField(default='', max_length=500),
        ),
    ]
