# Generated by Django 3.1.4 on 2021-04-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_delete_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_part',
            name='product_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
