# Generated by Django 3.1.4 on 2021-04-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_special_part_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestproduct',
            name='product_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
