# Generated by Django 3.1.4 on 2021-01-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_header_footerdata_footerlogo_describ_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='header_footerdata',
            name='copyRight',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='header_footerdata',
            name='copyRightBy',
            field=models.CharField(default='', max_length=50),
        ),
    ]
