# Generated by Django 3.1.4 on 2021-02-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0005_auto_20210130_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_images', models.ImageField(upload_to='slider_img/')),
            ],
        ),
        migrations.CreateModel(
            name='slider_part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('Header', models.CharField(max_length=30)),
                ('describe', models.TextField(max_length=200)),
                ('left_button', models.CharField(max_length=50)),
                ('right_button', models.CharField(max_length=50)),
            ],
        ),
    ]
