# Generated by Django 3.1.4 on 2021-04-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0006_ordershoped'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ordershoped',
        ),
    ]
