# Generated by Django 3.1.4 on 2021-02-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0006_slider_image_slider_part'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slider_image',
        ),
        migrations.AddField(
            model_name='slider_part',
            name='slider_images',
            field=models.ImageField(default='', upload_to='slider_img/'),
        ),
    ]
