# Generated by Django 3.1.4 on 2021-02-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0007_auto_20210208_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider_part',
            name='describe',
            field=models.TextField(max_length=500),
        ),
    ]
