# Generated by Django 3.1.4 on 2021-02-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0008_auto_20210208_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='shipping_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('details', models.TextField(max_length=350)),
            ],
        ),
    ]
