# Generated by Django 3.1.4 on 2021-02-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0010_special_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='feature_header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('menu1', models.CharField(max_length=50)),
                ('menu2', models.CharField(max_length=50)),
                ('menu3', models.CharField(max_length=50)),
                ('menu4', models.CharField(max_length=50)),
                ('menu5', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='feature_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(upload_to='feature_images/')),
                ('product_title', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
            ],
        ),
    ]
