# Generated by Django 3.1.4 on 2021-02-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0011_feature_header_feature_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='newProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='launchImages/')),
                ('productName', models.CharField(max_length=50)),
                ('details', models.TextField(max_length=250)),
                ('launchTitle', models.CharField(max_length=50)),
                ('month', models.CharField(default='', max_length=5)),
                ('day', models.CharField(default='', max_length=5)),
                ('year', models.CharField(default='', max_length=5)),
            ],
        ),
    ]
