# Generated by Django 3.1.4 on 2021-02-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0012_newproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproduct',
            name='day',
        ),
        migrations.RemoveField(
            model_name='newproduct',
            name='month',
        ),
        migrations.RemoveField(
            model_name='newproduct',
            name='year',
        ),
    ]
