# Generated by Django 3.1.4 on 2021-02-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0015_latestproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('personName', models.CharField(max_length=50)),
                ('personTitle', models.CharField(max_length=50)),
                ('personImg', models.ImageField(upload_to='testimonial/')),
                ('describe', models.TextField(max_length=220)),
                ('signature', models.CharField(max_length=15)),
            ],
        ),
    ]
