# Generated by Django 3.1.4 on 2021-02-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0016_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='bg_img',
            field=models.ImageField(default='', upload_to='testimonial/'),
        ),
    ]
