# Generated by Django 3.1.4 on 2021-02-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0017_testimonial_bg_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='bg_img',
        ),
    ]
