# Generated by Django 3.1.4 on 2021-02-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0018_remove_testimonial_bg_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=50)),
                ('img', models.ImageField(upload_to='blogImg/')),
                ('date', models.DateTimeField()),
                ('author_by', models.CharField(max_length=50)),
                ('like', models.CharField(max_length=50)),
                ('cmnt', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('describe', models.TextField(max_length=250)),
                ('button', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='header',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
