# Generated by Django 3.1.4 on 2021-02-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0019_auto_20210211_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_blog',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
