# Generated by Django 3.1.4 on 2021-03-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0020_auto_20210211_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature_product',
            name='product_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
