# Generated by Django 3.1.4 on 2021-03-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0021_feature_product_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordered_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('product_Code', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
